#!/usr/bin/python

import sys
from main import main
from Interpreter import Interpreter
from Context import Context
from Foundation.FoundationContext import FoundationContext

if len(sys.argv) == 2:
    filename = sys.argv[1]
    file = open(filename, 'r')
    content = file.read()
    lines = content.split("\n")
    context = Context(FoundationContext.simple())
    for line in lines:
        inter = Interpreter(context, line)
        inter.result()
else:
    main()
